runtime: python39
instance_class: F2

entrypoint: gunicorn -b :$PORT app.py:app

runtime_config:
  python_version: 3.9

env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "Hertzman01"
  MYSQL_HOST: "localhost"
  MYSQL_DATABASE: "gps"
